import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const tiktokSans = localFont({
  src: [
    { path: "./fonts/tiktok-sans/TikTokSans-Light.ttf", weight: "300", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-Medium.ttf", weight: "500", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-SemiBold.ttf", weight: "600", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-Bold.ttf", weight: "700", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-ExtraBold.ttf", weight: "800", style: "normal" },
    { path: "./fonts/tiktok-sans/TikTokSans-Black.ttf", weight: "900", style: "normal" },
  ],
  display: "swap",
});

const cardo = localFont({
  src: [
    { path: "./fonts/cardo/Cardo-Regular.ttf", weight: "400", style: "normal" },
    { path: "./fonts/cardo/Cardo-Italic.ttf", weight: "400", style: "italic" },
    { path: "./fonts/cardo/Cardo-Bold.ttf", weight: "700", style: "normal" },
  ],
  display: "swap",
  variable: "--font-cardo",
});

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${tiktokSans.className} ${cardo.variable}`}>{children}</body>
    </html>
  );
}
