import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

//! Update metadata to match your project
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const avenir = localFont({
  src: [
    {
      path: "../../public/fonts/Avenir/Avenir-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/fonts/Avenir/Avenir-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-avenir",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${avenir.variable} font-sans`}>
      <body>
        <div className="flex min-h-screen">
          {/* <Navbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
